[2024-06-22T15:46:10.491+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-22T15:46:10.516+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_to_s3.load_to_postgres manual__2024-06-22T15:32:58.871395+00:00 [queued]>
[2024-06-22T15:46:10.528+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_to_s3.load_to_postgres manual__2024-06-22T15:32:58.871395+00:00 [queued]>
[2024-06-22T15:46:10.529+0000] {taskinstance.py:2306} INFO - Starting attempt 4 of 6
[2024-06-22T15:46:10.720+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2024-06-22 15:32:58.871395+00:00
[2024-06-22T15:46:10.731+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4950) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-22T15:46:10.733+0000] {standard_task_runner.py:63} INFO - Started process 4952 to run task
[2024-06-22T15:46:10.731+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'postgres_to_s3', 'load_to_postgres', 'manual__2024-06-22T15:32:58.871395+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/postgres_s3.py', '--cfg-path', '/tmp/tmpf86nbhul']
[2024-06-22T15:46:10.734+0000] {standard_task_runner.py:91} INFO - Job 33: Subtask load_to_postgres
[2024-06-22T15:46:10.881+0000] {task_command.py:426} INFO - Running <TaskInstance: postgres_to_s3.load_to_postgres manual__2024-06-22T15:32:58.871395+00:00 [running]> on host 6380d29236af
[2024-06-22T15:46:11.127+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='protectorateog@gmail.com' AIRFLOW_CTX_DAG_OWNER='protectorate' AIRFLOW_CTX_DAG_ID='postgres_to_s3' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-06-22T15:32:58.871395+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-22T15:32:58.871395+00:00'
[2024-06-22T15:46:11.128+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-22T15:46:11.218+0000] {base.py:84} INFO - Using connection ID 'post_s3' for task execution.
[2024-06-22T15:46:11.620+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-22T15:46:11.623+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-22T15:46:11.637+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=postgres_to_s3, task_id=load_to_postgres, run_id=manual__2024-06-22T15:32:58.871395+00:00, execution_date=20240622T153258, start_date=20240622T154610, end_date=20240622T154611
[2024-06-22T15:46:11.837+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-22T15:46:11.874+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-22T15:46:11.987+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
