[2024-06-22T15:46:14.827+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-22T15:46:14.864+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_to_s3.load_to_s3 manual__2024-06-22T15:32:58.871395+00:00 [queued]>
[2024-06-22T15:46:14.877+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_to_s3.load_to_s3 manual__2024-06-22T15:32:58.871395+00:00 [queued]>
[2024-06-22T15:46:14.878+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-06-22T15:46:14.938+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_to_s3> on 2024-06-22 15:32:58.871395+00:00
[2024-06-22T15:46:14.951+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4964) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-22T15:46:14.949+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'postgres_to_s3', 'load_to_s3', 'manual__2024-06-22T15:32:58.871395+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/postgres_s3.py', '--cfg-path', '/tmp/tmpmn2j5kxh']
[2024-06-22T15:46:14.952+0000] {standard_task_runner.py:63} INFO - Started process 4966 to run task
[2024-06-22T15:46:14.953+0000] {standard_task_runner.py:91} INFO - Job 34: Subtask load_to_s3
[2024-06-22T15:46:15.052+0000] {task_command.py:426} INFO - Running <TaskInstance: postgres_to_s3.load_to_s3 manual__2024-06-22T15:32:58.871395+00:00 [running]> on host 6380d29236af
[2024-06-22T15:46:15.245+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='protectorateog@gmail.com' AIRFLOW_CTX_DAG_OWNER='protectorate' AIRFLOW_CTX_DAG_ID='postgres_to_s3' AIRFLOW_CTX_TASK_ID='load_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-06-22T15:32:58.871395+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-22T15:32:58.871395+00:00'
[2024-06-22T15:46:15.247+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-22T15:46:15.274+0000] {base.py:84} INFO - Using connection ID 'post_s3' for task execution.
[2024-06-22T15:46:15.435+0000] {base.py:84} INFO - Using connection ID 'simple_store' for task execution.
[2024-06-22T15:46:15.436+0000] {connection_wrapper.py:384} INFO - AWS Connection (conn_id='simple_store', conn_type='aws') credentials retrieved from login and password.
[2024-06-22T15:46:22.430+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-06-22T15:46:22.432+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-22T15:46:22.449+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=postgres_to_s3, task_id=load_to_s3, run_id=manual__2024-06-22T15:32:58.871395+00:00, execution_date=20240622T153258, start_date=20240622T154614, end_date=20240622T154622
[2024-06-22T15:46:22.650+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-22T15:46:22.675+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-22T15:46:22.712+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
