[2024-06-15T10:07:24.002+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-15T10:07:24.033+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: csv_to_s3_dag.extract_csv manual__2024-06-15T10:04:48.358012+00:00 [queued]>
[2024-06-15T10:07:24.052+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: csv_to_s3_dag.extract_csv manual__2024-06-15T10:04:48.358012+00:00 [queued]>
[2024-06-15T10:07:24.053+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 6
[2024-06-15T10:07:24.108+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_csv> on 2024-06-15 10:04:48.358012+00:00
[2024-06-15T10:07:24.126+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'csv_to_s3_dag', 'extract_csv', 'manual__2024-06-15T10:04:48.358012+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/***_dag.py', '--cfg-path', '/tmp/tmptd65uw50']
[2024-06-15T10:07:24.131+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask extract_csv
[2024-06-15T10:07:24.131+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2443) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-15T10:07:24.133+0000] {standard_task_runner.py:63} INFO - Started process 2445 to run task
[2024-06-15T10:07:24.269+0000] {task_command.py:426} INFO - Running <TaskInstance: csv_to_s3_dag.extract_csv manual__2024-06-15T10:04:48.358012+00:00 [running]> on host d4d3ae2e009b
[2024-06-15T10:07:24.506+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='protectorate' AIRFLOW_CTX_DAG_ID='csv_to_s3_dag' AIRFLOW_CTX_TASK_ID='extract_csv' AIRFLOW_CTX_EXECUTION_DATE='2024-06-15T10:04:48.358012+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-15T10:04:48.358012+00:00'
[2024-06-15T10:07:24.509+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-15T10:07:24.541+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-15T10:07:24.542+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/airflow_dag.py", line 10, in extract_csv
    df = pd.read_csv(csv_path, nrows=50)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/airflow/british_air_sentiments.csv'
[2024-06-15T10:07:24.569+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=csv_to_s3_dag, task_id=extract_csv, run_id=manual__2024-06-15T10:04:48.358012+00:00, execution_date=20240615T100448, start_date=20240615T100724, end_date=20240615T100724
[2024-06-15T10:07:24.624+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task extract_csv ([Errno 2] No such file or directory: '/home/airflow/british_air_sentiments.csv'; 2445)
[2024-06-15T10:07:24.670+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-15T10:07:24.759+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-15T10:07:24.853+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
